# Generated by Django 5.0.6 on 2024-07-02 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_images', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.TextField()),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='userpannel.userimagegeneration')),
            ],
        ),
        migrations.CreateModel(
            name='UserMasterPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('prompt', models.TextField(max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(max_length=1500)),
                ('master_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprompts', to='userpannel.usermasterprompt')),
            ],
        ),
        migrations.AddField(
            model_name='userimagegeneration',
            name='sub_prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='userpannel.usersubprompt'),
        ),
    ]
