# Generated by Django 5.0.6 on 2024-07-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpannel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('credit', models.FloatField(default=0)),
                ('image', models.ImageField(null=True, upload_to='profile_images/')),
            ],
        ),
    ]
